# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tultaria/animations/attack_magic_3_right_loop/zzz/apply_frame {frame: 60}
scoreboard players add @s aj.attack_magic_3_right_loop.frame 1