# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.ecual.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'ecual', 'function_path': 'animated_java:ecual/animations/9_0_water_wall/apply_frame'}
$execute store result storage aj:temp frame int 1 run scoreboard players set @s aj.9_0_water_wall.frame $(frame)
execute at @s run function animated_java:ecual/animations/9_0_water_wall/zzz/apply_frame with storage aj:temp