# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.axia.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'axia', 'function_path': 'animated_java:axia/animations/6_1_moving_back/play'}
tag @s add aj.axia.animation.6_1_moving_back.playing
scoreboard players set @s aj.6_1_moving_back.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:axia/animations/6_1_moving_back/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only