# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.axia.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'axia', 'function_path': 'animated_java:axia/animations/pause_all'}
tag @s remove aj.axia.animation.1_0_idle.playing
tag @s remove aj.axia.animation.1_1_idle_rare.playing
tag @s remove aj.axia.animation.2_0_normal_slash.playing
tag @s remove aj.axia.animation.3_0_triple_slash.playing
tag @s remove aj.axia.animation.4_0_naginagi.playing
tag @s remove aj.axia.animation.6_0_moving_forward.playing
tag @s remove aj.axia.animation.6_1_moving_back.playing
tag @s remove aj.axia.animation.7_0_moving_iai.playing
tag @s remove aj.axia.animation.8_0_moving_spin.playing
tag @s remove aj.axia.animation.9_0_zangekihou.playing
tag @s remove aj.axia.animation.10_0_warp_start.playing
tag @s remove aj.axia.animation.10_1_warp_slash_0.playing
tag @s remove aj.axia.animation.10_2_warp_slash_1.playing
tag @s remove aj.axia.animation.10_3_warp_slash_2.playing
tag @s remove aj.axia.animation.11_0_dimension_slash.playing
tag @s remove aj.axia.animation.12_0_kourai.playing
tag @s remove aj.axia.animation.13_0_damage_1.playing
tag @s remove aj.axia.animation.13_1_damage_2.playing
tag @s remove aj.axia.animation.14_0_opening_attack.playing
tag @s remove aj.axia.animation.15_0_former_ending.playing