# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.ecual.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'ecual', 'function_path': 'animated_java:ecual/animations/6_0_moving/next_frame'}
execute if score @s aj.6_0_moving.frame matches 56.. run scoreboard players set @s aj.6_0_moving.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.6_0_moving.frame
execute at @s run function animated_java:ecual/animations/6_0_moving/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.6_0_moving.frame 1