# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.tultaria.root] run return 0
execute on passengers if entity @s[tag=aj.tultaria.data] unless data entity @s {data:{rigHash: '39a84c32e100bee1139f71782f241deb69648df7acefdd7d4e271361536ed246'}} on vehicle run function animated_java:tultaria/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1