# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.1_0_idle.frame dummy
scoreboard objectives add aj.1_1_idle_rare.frame dummy
scoreboard objectives add aj.2_0_chill_rain.frame dummy
scoreboard objectives add aj.3_0_crystal_turret.frame dummy
scoreboard objectives add aj.4_0_summon_book.frame dummy
scoreboard objectives add aj.5_0_shining_ray.frame dummy
scoreboard objectives add aj.5_1_water_bullet.frame dummy
scoreboard objectives add aj.6_0_moving.frame dummy
scoreboard objectives add aj.7_0_holy_ray.frame dummy
scoreboard objectives add aj.8_0_quietus_rain.frame dummy
scoreboard objectives add aj.11_0_damage_1.frame dummy
scoreboard objectives add aj.11_1_damage_2.frame dummy
scoreboard objectives add aj.12_0_opening_attack.frame dummy
scoreboard objectives add aj.13_0_former_ending.frame dummy
scoreboard objectives add aj.9_0_water_wall.frame dummy
scoreboard objectives add aj.10_0_hydro_storm.frame dummy