# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.axia.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'axia', 'function_path': 'animated_java:axia/animations/10_0_warp_start/apply_frame'}
$execute store result storage aj:temp frame int 1 run scoreboard players set @s aj.10_0_warp_start.frame $(frame)
execute at @s run function animated_java:axia/animations/10_0_warp_start/zzz/apply_frame with storage aj:temp