# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.ecual.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'ecual', 'function_path': 'animated_java:ecual/animations/2_0_chill_rain/play'}
tag @s add aj.ecual.animation.2_0_chill_rain.playing
scoreboard players set @s aj.2_0_chill_rain.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:ecual/animations/2_0_chill_rain/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only