# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.ecual.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'ecual', 'function_path': 'animated_java:ecual/animations/3_0_crystal_turret/next_frame'}
execute if score @s aj.3_0_crystal_turret.frame matches 81.. run scoreboard players set @s aj.3_0_crystal_turret.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.3_0_crystal_turret.frame
execute at @s run function animated_java:ecual/animations/3_0_crystal_turret/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.3_0_crystal_turret.frame 1