# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.neutral_air.frame dummy
scoreboard objectives add aj.attack_magic_1_right.frame dummy
scoreboard objectives add aj.attack_magic_1_left.frame dummy
scoreboard objectives add aj.attack_magic_2_right.frame dummy
scoreboard objectives add aj.attack_magic_2_left.frame dummy
scoreboard objectives add aj.attack_magic_3_right.frame dummy
scoreboard objectives add aj.attack_magic_3_right_loop.frame dummy
scoreboard objectives add aj.attack_melee_1.frame dummy
scoreboard objectives add aj.attack_melee_2.frame dummy
scoreboard objectives add aj.attack_melee_3.frame dummy
scoreboard objectives add aj.attack_melee_4_windup.frame dummy
scoreboard objectives add aj.attack_melee_4_active.frame dummy
scoreboard objectives add aj.dodge_back.frame dummy
scoreboard objectives add aj.dodge_side.frame dummy
scoreboard objectives add aj.death.frame dummy