# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.axia.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'axia', 'function_path': 'animated_java:axia/animations/7_0_moving_iai/next_frame'}
execute if score @s aj.7_0_moving_iai.frame matches 66.. run scoreboard players set @s aj.7_0_moving_iai.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.7_0_moving_iai.frame
execute at @s run function animated_java:axia/animations/7_0_moving_iai/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.7_0_moving_iai.frame 1