# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.ecual.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'ecual', 'function_path': 'animated_java:ecual/animations/8_0_quietus_rain/next_frame'}
execute if score @s aj.8_0_quietus_rain.frame matches 151.. run scoreboard players set @s aj.8_0_quietus_rain.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.8_0_quietus_rain.frame
execute at @s run function animated_java:ecual/animations/8_0_quietus_rain/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.8_0_quietus_rain.frame 1