# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.tultaria.locator', 'aj.tultaria.locator.locator_right_hand']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:tultaria/zzz/2
data modify entity @s data.locators.locator_right_hand.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.tultaria.locator', 'aj.tultaria.locator.locator_left_hand']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:tultaria/zzz/3
data modify entity @s data.locators.locator_left_hand.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.bust] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bust set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.left_wing] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_wing set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.right_wing] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_wing set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.right_ring] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_ring set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.sword] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sword set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.right_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.left_ring] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_ring set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.left_hand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_hand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.leftfoot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftfoot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.leftleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leftleg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.rightfoot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightfoot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.rightleg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_rightleg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.skirt_right_back] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_right_back set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.skirt_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.skirt_left_back] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_left_back set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.skirt_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.skirt_back_middle] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_back_middle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.skirt_front_middle] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_skirt_front_middle set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.tultaria.bone.lower] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_lower set from storage aj:uuid main.out