# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.new
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data merge entity @s {}
tag @s add RW.ModelLocator.RightHand