# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tellraw @a ["",[{"text":"[","color":"gray"},{"text":"AJ","color":"aqua"},{"text":"] "}],{"text":"Error: ","color":"red"},{"text":"No variants are available.","color":"red"}]
function animated_java:tultaria/remove/this