# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.axia.root] run return 0
execute on passengers if entity @s[tag=aj.axia.data] unless data entity @s {data:{rigHash: 'd07bcee3d1cf7185c652ca19808a8fbc0de62422f407f70a9a6355c43f9451f8'}} on vehicle run function animated_java:axia/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1