# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.ecual.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'ecual', 'function_path': 'animated_java:ecual/animations/12_0_opening_attack/stop'}
tag @s remove aj.ecual.animation.12_0_opening_attack.playing
scoreboard players set @s aj.12_0_opening_attack.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:ecual/animations/12_0_opening_attack/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only