# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.axia.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'axia', 'function_path': 'animated_java:axia/animations/12_0_kourai/stop'}
tag @s remove aj.axia.animation.12_0_kourai.playing
scoreboard players set @s aj.12_0_kourai.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:axia/animations/12_0_kourai/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only