# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:uuid temp set value {0:0,1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0,a:0,b:0,c:0,d:0,e:0,f:0}
$data modify storage aj:uuid main.in set value $(UUID)
execute store result score 0= aj.i store result score 1= aj.i run data get storage aj:uuid main.in[0]
execute store result storage aj:uuid temp.0 int 1 run scoreboard players operation 0= aj.i %= 256 aj.i
execute store result score 2= aj.i run scoreboard players operation 1= aj.i /= 256 aj.i
execute store result storage aj:uuid temp.1 int 1 run scoreboard players operation 1= aj.i %= 256 aj.i
execute store result score 3= aj.i run scoreboard players operation 2= aj.i /= 256 aj.i
execute store result storage aj:uuid temp.2 int 1 run scoreboard players operation 2= aj.i %= 256 aj.i
execute store result storage aj:uuid temp.3 int 1 run scoreboard players operation 3= aj.i /= 256 aj.i
execute store result score 0= aj.i store result score 1= aj.i run data get storage aj:uuid main.in[1]
execute store result storage aj:uuid temp.4 int 1 run scoreboard players operation 0= aj.i %= 256 aj.i
execute store result score 2= aj.i run scoreboard players operation 1= aj.i /= 256 aj.i
execute store result storage aj:uuid temp.5 int 1 run scoreboard players operation 1= aj.i %= 256 aj.i
execute store result score 3= aj.i run scoreboard players operation 2= aj.i /= 256 aj.i
execute store result storage aj:uuid temp.6 int 1 run scoreboard players operation 2= aj.i %= 256 aj.i
execute store result storage aj:uuid temp.7 int 1 run scoreboard players operation 3= aj.i /= 256 aj.i
execute store result score 0= aj.i store result score 1= aj.i run data get storage aj:uuid main.in[2]
execute store result storage aj:uuid temp.8 int 1 run scoreboard players operation 0= aj.i %= 256 aj.i
execute store result score 2= aj.i run scoreboard players operation 1= aj.i /= 256 aj.i
execute store result storage aj:uuid temp.9 int 1 run scoreboard players operation 1= aj.i %= 256 aj.i
execute store result score 3= aj.i run scoreboard players operation 2= aj.i /= 256 aj.i
execute store result storage aj:uuid temp.a int 1 run scoreboard players operation 2= aj.i %= 256 aj.i
execute store result storage aj:uuid temp.b int 1 run scoreboard players operation 3= aj.i /= 256 aj.i
execute store result score 0= aj.i store result score 1= aj.i run data get storage aj:uuid main.in[3]
execute store result storage aj:uuid temp.c int 1 run scoreboard players operation 0= aj.i %= 256 aj.i
execute store result score 2= aj.i run scoreboard players operation 1= aj.i /= 256 aj.i
execute store result storage aj:uuid temp.d int 1 run scoreboard players operation 1= aj.i %= 256 aj.i
execute store result score 3= aj.i run scoreboard players operation 2= aj.i /= 256 aj.i
execute store result storage aj:uuid temp.e int 1 run scoreboard players operation 2= aj.i %= 256 aj.i
execute store result storage aj:uuid temp.f int 1 run scoreboard players operation 3= aj.i /= 256 aj.i
function animated_java:global/internal/gu/zzz/0 with storage aj:uuid temp
function animated_java:global/internal/gu/zzz/1 with storage aj:uuid temp