# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tultaria/animations/neutral_air/zzz/apply_frame {frame: 60}
scoreboard players add @s aj.neutral_air.frame 1