# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.i dummy
scoreboard objectives add aj.id dummy
scoreboard objectives add aj.is_rig_loaded dummy
scoreboard objectives add aj.tween_duration dummy
scoreboard players add aj.last_id aj.id 0
data modify storage aj:temp args set value {}
scoreboard players reset * aj.is_rig_loaded
function #animated_java:global/on_load