# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.ecual.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'ecual', 'function_path': 'animated_java:ecual/animations/pause_all'}
tag @s remove aj.ecual.animation.1_0_idle.playing
tag @s remove aj.ecual.animation.1_1_idle_rare.playing
tag @s remove aj.ecual.animation.2_0_chill_rain.playing
tag @s remove aj.ecual.animation.3_0_crystal_turret.playing
tag @s remove aj.ecual.animation.4_0_summon_book.playing
tag @s remove aj.ecual.animation.5_0_shining_ray.playing
tag @s remove aj.ecual.animation.5_1_water_bullet.playing
tag @s remove aj.ecual.animation.6_0_moving.playing
tag @s remove aj.ecual.animation.7_0_holy_ray.playing
tag @s remove aj.ecual.animation.8_0_quietus_rain.playing
tag @s remove aj.ecual.animation.11_0_damage_1.playing
tag @s remove aj.ecual.animation.11_1_damage_2.playing
tag @s remove aj.ecual.animation.12_0_opening_attack.playing
tag @s remove aj.ecual.animation.13_0_former_ending.playing
tag @s remove aj.ecual.animation.9_0_water_wall.playing
tag @s remove aj.ecual.animation.10_0_hydro_storm.playing