# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.wing_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.wing_right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.wing_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.wing_left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.blade] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_blade set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.arm_right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.arm_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.arm_left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.arm_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.ear_edge_a1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_edge_a1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.ear_edge_a2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_edge_a2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.ear_edge_b1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_edge_b1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.ear_edge_b2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_edge_b2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.ear_right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.ear_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.ear_edge_a3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_edge_a3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.ear_edge_a4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_edge_a4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.ear_edge_b3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_edge_b3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.ear_edge_b4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_edge_b4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.ear_left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.ear_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.body_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.leg_left_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.leg_left_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.leg_right_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.leg_right_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.coat_downer] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_coat_downer set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.axia.bone.body_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_2 set from storage aj:uuid main.out