# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.tultaria.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'tultaria', 'function_path': 'animated_java:tultaria/animations/pause_all'}
tag @s remove aj.tultaria.animation.neutral_air.playing
tag @s remove aj.tultaria.animation.attack_magic_1_right.playing
tag @s remove aj.tultaria.animation.attack_magic_1_left.playing
tag @s remove aj.tultaria.animation.attack_magic_2_right.playing
tag @s remove aj.tultaria.animation.attack_magic_2_left.playing
tag @s remove aj.tultaria.animation.attack_magic_3_right.playing
tag @s remove aj.tultaria.animation.attack_magic_3_right_loop.playing
tag @s remove aj.tultaria.animation.attack_melee_1.playing
tag @s remove aj.tultaria.animation.attack_melee_2.playing
tag @s remove aj.tultaria.animation.attack_melee_3.playing
tag @s remove aj.tultaria.animation.attack_melee_4_windup.playing
tag @s remove aj.tultaria.animation.attack_melee_4_active.playing
tag @s remove aj.tultaria.animation.dodge_back.playing
tag @s remove aj.tultaria.animation.dodge_side.playing
tag @s remove aj.tultaria.animation.death.playing