# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ecual.root] run return 0
execute on passengers if entity @s[tag=aj.ecual.data] unless data entity @s {data:{rigHash: 'af89bb2a761f291673a0477dc8e73538b231f881c00742cdd6bd30c7e7d9dda6'}} on vehicle run function animated_java:ecual/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1