# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.ecual.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:ecual/as_root/pre_tick
execute if entity @s[tag=aj.ecual.animation.1_0_idle.playing] run function animated_java:ecual/animations/1_0_idle/zzz/on_tick
execute if entity @s[tag=aj.ecual.animation.1_1_idle_rare.playing] run function animated_java:ecual/animations/1_1_idle_rare/zzz/on_tick
execute if entity @s[tag=aj.ecual.animation.2_0_chill_rain.playing] run function animated_java:ecual/animations/2_0_chill_rain/zzz/on_tick
execute if entity @s[tag=aj.ecual.animation.3_0_crystal_turret.playing] run function animated_java:ecual/animations/3_0_crystal_turret/zzz/on_tick
execute if entity @s[tag=aj.ecual.animation.4_0_summon_book.playing] run function animated_java:ecual/animations/4_0_summon_book/zzz/on_tick
execute if entity @s[tag=aj.ecual.animation.5_0_shining_ray.playing] run function animated_java:ecual/animations/5_0_shining_ray/zzz/on_tick
execute if entity @s[tag=aj.ecual.animation.5_1_water_bullet.playing] run function animated_java:ecual/animations/5_1_water_bullet/zzz/on_tick
execute if entity @s[tag=aj.ecual.animation.6_0_moving.playing] run function animated_java:ecual/animations/6_0_moving/zzz/on_tick
execute if entity @s[tag=aj.ecual.animation.7_0_holy_ray.playing] run function animated_java:ecual/animations/7_0_holy_ray/zzz/on_tick
execute if entity @s[tag=aj.ecual.animation.8_0_quietus_rain.playing] run function animated_java:ecual/animations/8_0_quietus_rain/zzz/on_tick
execute if entity @s[tag=aj.ecual.animation.11_0_damage_1.playing] run function animated_java:ecual/animations/11_0_damage_1/zzz/on_tick
execute if entity @s[tag=aj.ecual.animation.11_1_damage_2.playing] run function animated_java:ecual/animations/11_1_damage_2/zzz/on_tick
execute if entity @s[tag=aj.ecual.animation.12_0_opening_attack.playing] run function animated_java:ecual/animations/12_0_opening_attack/zzz/on_tick
execute if entity @s[tag=aj.ecual.animation.13_0_former_ending.playing] run function animated_java:ecual/animations/13_0_former_ending/zzz/on_tick
execute if entity @s[tag=aj.ecual.animation.9_0_water_wall.playing] run function animated_java:ecual/animations/9_0_water_wall/zzz/on_tick
execute if entity @s[tag=aj.ecual.animation.10_0_hydro_storm.playing] run function animated_java:ecual/animations/10_0_hydro_storm/zzz/on_tick
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:ecual/as_root/post_tick