# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tultaria/remove/zzz/kill with entity @s data.locators.locator_right_hand
function animated_java:tultaria/remove/zzz/kill with entity @s data.locators.locator_left_hand