# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:tultaria/root/zzz/2 with entity @s data.locators.locator_right_hand
function animated_java:tultaria/root/zzz/4 with entity @s data.locators.locator_left_hand